Ti.App.iconCodes = {
  6: 'img/climacons/Cloud-Rain.svg', //  'mixed rain and sleet'
  7: 'img/climacons/Cloud-Snow-Alt.svg', //  'mixed snow and sleet'
  8: 'img/climacons/Cloud-Drizzle-Alt.svg', //  'freezing drizzle'
  9: 'img/climacons/Cloud-Drizzle-Alt.svg', //  'drizzle'
  10: 'img/climacons/Cloud-Rain.svg', //  'freezing rain'
  11: 'img/climacons/Umbrella.svg', //  'showers'
  12: 'img/climacons/Umbrella.svg', //  'showers'
  13: 'img/climacons/Cloud-Snow.svg', //  'snow flurries'
  14: 'img/climacons/Cloud-Snow.svg', //  'light snow showers'
  15: 'img/climacons/Cloud-Snow.svg', //  'blowing snow'
  16: 'img/climacons/Cloud-Snow.svg', //  'snow'
  17: 'img/climacons/Cloud-Hail-Alt.svg', //  'hail'
  18: 'img/climacons/Cloud-Rain.svg', //  'sleet'
  19: 'img/climacons/Wind.svg', //  'dust'
  20: 'img/climacons/Cloud-Fog.svg', //  'foggy'
  21: 'img/climacons/Cloud-Fog-Alt.svg', //  'haze'
  22: 'img/climacons/Cloud-Fog-Alt.svg', //  'smoky'
  23: 'img/climacons/Wind.svg', //  'blustery'
  24: 'img/climacons/Cloud-Wind.svg', //  'windy'
  25: 'img/climacons/Thermometer-Zero.svg', //  'cold'
  26: 'img/climacons/Cloud.svg', //  'cloudy'
  27: 'img/climacons/Cloud-Moon.svg', //  'mostly cloudy (night)'
  28: 'img/climacons/Cloud-Sun.svg', //  'mostly cloudy (day)'
  29: 'img/climacons/Cloud-Moon.svg', //  'partly cloudy (night)'
  30: 'img/climacons/Cloud-Sun.svg', //  'partly cloudy (day)'
  31: 'img/climacons/Moon.svg', //  'clear (night)'
  32: 'img/climacons/Sun.svg', //  'sunny'
  33: 'img/climacons/Moon.svg', //  'fair (night)'
  34: 'img/climacons/Sun.svg', //  'fair (day)'
  35: 'img/climacons/Cloud-Hail.svg', //  'mixed rain and hail'
  36: 'img/climacons/Thermometer-100.svg', //  'hot'
  37: 'img/climacons/Cloud-Lightning.svg', //  'isolated thunderstorms'
  38: 'img/climacons/Cloud-Lightning.svg', //  'scattered thunderstorms'
  39: 'img/climacons/Cloud-Lightning.svg', //  'scattered thunderstorms'
  40: 'img/climacons/Umbrella.svg', //  'scattered showers'
  41: 'img/climacons/Snowflake.svg', //  'heavy snow'
  42: 'img/climacons/Cloud-Snow.svg', //  'scattered snow showers'
  43: 'img/climacons/Cloud-Snow-Alt.svg', //  'heavy snow'
  44: 'img/climacons/Cloud-Sun.svg', //  'partly cloudy'
  45: 'img/climacons/Cloud-Lightning.svg', //  'thundershowers'
  46: 'img/climacons/Cloud-Snow.svg', //  'snow showers'
  47: 'img/climacons/Cloud-Lightning.svg', //  'isolated thundershowers'
  3200: 'img/climacons/Sun.svg' //  'not available'
}