INSERT INTO 'icon_definitions'
SELECT 0 AS id, 'tornado' AS desc, 'img/climacons/Tornado.svg' AS resource
UNION SELECT 1, 'tropical storm', 'img/climacons/Cloud-Rain.svg'
UNION SELECT 2, 'hurricane', '/img/climacons/Tornado.svg'
UNION SELECT 3, 'severe thunderstorms', 'img/climacons/Cloud-Lightning.svg'
UNION SELECT 4, 'thunderstorms', '/img/climacons/Cloud-Lightning.svg'
UNION SELECT 5, 'mixed rain and snow', 'img/climacons/Cloud-Snow-Alt.svg'
UNION SELECT 6,  'mixed rain and sleet', 'img/climacons/Cloud-Rain.svg'
UNION SELECT 7,  'mixed snow and sleet', 'img/climacons/Cloud-Snow-Alt.svg'
UNION SELECT 8,  'freezing drizzle', 'img/climacons/Cloud-Drizzle-Alt.svg'
UNION SELECT 9,  'drizzle', 'img/climacons/Cloud-Drizzle-Alt.svg'
UNION SELECT 10,  'freezing rain', 'img/climacons/Cloud-Rain.svg'
UNION SELECT 11,  'showers', 'img/climacons/Umbrella.svg'
UNION SELECT 12,  'showers', 'img/climacons/Umbrella.svg'
UNION SELECT 13,  'snow flurries', 'img/climacons/Cloud-Snow.svg'
UNION SELECT 14,  'light snow showers', 'img/climacons/Cloud-Snow.svg'
UNION SELECT 15,  'blowing snow', 'img/climacons/Cloud-Snow.svg'
UNION SELECT 16,  'snow', 'img/climacons/Cloud-Snow.svg'
UNION SELECT 17,  'hail', 'img/climacons/Cloud-Hail-Alt.svg'
UNION SELECT 18,  'sleet', 'img/climacons/Cloud-Rain.svg'
UNION SELECT 19,  'dust', 'img/climacons/Wind.svg'
UNION SELECT 20,  'foggy', 'img/climacons/Cloud-Fog.svg'
UNION SELECT 21,  'haze', 'img/climacons/Cloud-Fog-Alt.svg'
UNION SELECT 22,  'smoky', 'img/climacons/Cloud-Fog-Alt.svg'
UNION SELECT 23,  'blustery', 'img/climacons/Wind.svg'
UNION SELECT 24,  'windy', 'img/climacons/Cloud-Wind.svg'
UNION SELECT 25,  'cold', 'img/climacons/Thermometer-Zero.svg'
UNION SELECT 26,  'cloudy', 'img/climacons/Cloud.svg'
UNION SELECT 27,  'mostly cloudy (night)', 'img/climacons/Cloud-Moon.svg'
UNION SELECT 28,  'mostly cloudy (day)', 'img/climacons/Cloud-Sun.svg'
UNION SELECT 29,  'partly cloudy (night)', 'img/climacons/Cloud-Moon.svg'
UNION SELECT 30,  'partly cloudy (day)', 'img/climacons/Cloud-Sun.svg'
UNION SELECT 31,  'clear (night)', 'img/climacons/Moon.svg'
UNION SELECT 32,  'sunny', 'img/climacons/Sun.svg'
UNION SELECT 33,  'fair (night)', 'img/climacons/Moon.svg'
UNION SELECT 34,  'fair (day)', 'img/climacons/Sun.svg'
UNION SELECT 35,  'mixed rain and hail', 'img/climacons/Cloud-Hail.svg'
UNION SELECT 36,  'hot', 'img/climacons/Thermometer-100.svg'
UNION SELECT 37,  'isolated thunderstorms', 'img/climacons/Cloud-Lightning.svg'
UNION SELECT 38,  'scattered thunderstorms', 'img/climacons/Cloud-Lightning.svg'
UNION SELECT 39,  'scattered thunderstorms', 'img/climacons/Cloud-Lightning.svg'
UNION SELECT 40,  'scattered showers', 'img/climacons/Umbrella.svg'
UNION SELECT 41,  'heavy snow', 'img/climacons/Snowflake.svg'
UNION SELECT 42,  'scattered snow showers', 'img/climacons/Cloud-Snow.svg'
UNION SELECT 43,  'heavy snow', 'img/climacons/Cloud-Snow-Alt.svg'
UNION SELECT 44,  'partly cloudy', 'img/climacons/Cloud-Sun.svg'
UNION SELECT 45,  'thundershowers', 'img/climacons/Cloud-Lightning.svg'
UNION SELECT 46,  'snow showers', 'img/climacons/Cloud-Snow.svg'
UNION SELECT 47,  'isolated thundershowers', 'img/climacons/Cloud-Lightning.svg'
UNION SELECT 3200,  'not available', 'img/climacons/Sun.svg'
